export const AUTH_USER_FETCH_USER = "AUTH_USER_FETCH_USER";
export type AUTH_USER_FETCH_USER = typeof AUTH_USER_FETCH_USER;

export const NETWORK_SET_CONNECTION_STATE = "NETWORK_SET_CONNECTION_STATE";
export type NETWORK_SET_CONNECTION_STATE = typeof NETWORK_SET_CONNECTION_STATE;

export const APP_SET_LOADING_USER_STATE = "APP_SET_LOADING_STATE";
export type APP_SET_LOADING_USER_STATE = typeof APP_SET_LOADING_USER_STATE;

export const UPLOAD_DIALOG_OPEN = "UPLOAD_DIALOG_OPEN";
export type UPLOAD_DIALOG_OPEN = typeof UPLOAD_DIALOG_OPEN;

export const UPLOAD_DIALOG_CLOSE = "UPLOAD_DIALOG_CLOSE";
export type UPLOAD_DIALOG_CLOSE = typeof UPLOAD_DIALOG_CLOSE;
