export const AUTH_USER_FETCH_USER = "AUTH_USER_FETCH_USER";
export type AUTH_USER_FETCH_USER = typeof AUTH_USER_FETCH_USER;

export const AUTH_USER_LOGIN = "AUTH_USER_LOGIN";
export type AUTH_USER_LOGIN = typeof AUTH_USER_LOGIN;

export const AUTH_USER_LOGOUT = "AUTH_USER_LOGOUT";
export type AUTH_USER_LOGOUT = typeof AUTH_USER_LOGOUT;
